#!/usr/bin/env bash
# Generated by deploylane — run once on the server with sudo
# Usage: sudo bash {{deploy_dir}}/.deploylane/install.sh
set -euo pipefail

APP_NAME="{{app_name}}"
DEPLOY_USER="{{deploy_user}}"
DEPLOY_DIR="{{deploy_dir}}"
STRATEGY="{{strategy}}"
NGINX_SNIPPETS="/etc/nginx/snippets"
NGINX_SITES="/etc/nginx/sites-available"
SUDOERS_DIR="/etc/sudoers.d"

die() { echo "ERROR: $*" >&2; exit 1; }
ok()  { echo "  ✓ $*"; }

[ "$(id -u)" -eq 0 ] || die "Run with sudo: sudo bash $0"

echo "deploylane install — ${APP_NAME} (strategy: ${STRATEGY})"
echo ""

# ── Deploy dir ──────────────────────────────────────────────────────────────
mkdir -p "${DEPLOY_DIR}"
chown "${DEPLOY_USER}:${DEPLOY_USER}" "${DEPLOY_DIR}"
ok "deploy dir: ${DEPLOY_DIR}"

if [ "${STRATEGY}" = "bluegreen" ]; then
  # ── Nginx snippets ────────────────────────────────────────────────────────
  mkdir -p "${NGINX_SNIPPETS}"

  cp "${DEPLOY_DIR}/.deploylane/nginx/${APP_NAME}-upstream-blue.conf"  "${NGINX_SNIPPETS}/"
  cp "${DEPLOY_DIR}/.deploylane/nginx/${APP_NAME}-upstream-green.conf" "${NGINX_SNIPPETS}/"
  ok "nginx snippets: ${NGINX_SNIPPETS}/${APP_NAME}-upstream-{blue,green}.conf"

  # Initial symlink → blue
  ln -sf "${NGINX_SNIPPETS}/${APP_NAME}-upstream-blue.conf" \
         "${NGINX_SNIPPETS}/${APP_NAME}-upstream.conf"
  ok "nginx symlink: ${APP_NAME}-upstream.conf → blue (initial)"

  # ── sites-available include ───────────────────────────────────────────────
  mkdir -p "${NGINX_SITES}"
  cp "${DEPLOY_DIR}/.deploylane/nginx/00-${APP_NAME}-upstream.conf" \
     "${NGINX_SITES}/"
  ok "nginx site include: ${NGINX_SITES}/00-${APP_NAME}-upstream.conf"

  # ── sudoers ───────────────────────────────────────────────────────────────
  SUDOERS_FILE="${SUDOERS_DIR}/nginx-bg-switch-${APP_NAME}"
  cp "${DEPLOY_DIR}/.deploylane/sudoers/nginx-bg-switch" "${SUDOERS_FILE}"
  chmod 440 "${SUDOERS_FILE}"
  visudo -cf "${SUDOERS_FILE}" || die "sudoers syntax error: ${SUDOERS_FILE}"
  ok "sudoers: ${SUDOERS_FILE}"

  # ── nginx reload ──────────────────────────────────────────────────────────
  nginx -t && systemctl reload nginx
  ok "nginx reloaded"
fi

echo ""
echo "Install complete — ${APP_NAME}"
echo "  Next: dlane deploy push ${APP_NAME} (push .env + compose)"
